language: python
python:
    - "3.5"
    - "3.6"
    # - "3.7dev" # fails on travis for now

dist: trusty
sudo: required

before_script:
  - pip install pipenv
  - pipenv install --dev
  - sh fix_pyzmq.sh

script: pipenv run py.test tests
