language: python
python:
    - "3.5"
    - "3.6"
    # - "3.7dev" # fails on travis for now

dist: trusty
sudo: required

before_script:
  - pip install pipenv
  - pipenv install --dev
  - sh fix_pyzmq.sh

script: pipenv run py.test --cov=messagequeue -v tests

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then
          coveralls;
      fi
