language: bash

dist: trusty
sudo: required

env:
  - KAFKA_VERSION=1.0.0 SCALA_VERSION=2.12

services:
  - docker

before_script:
  - docker build -t d53dave/kafka .
  - docker run -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost --env ADVERTISED_PORT=9092 spotify/kafka
  - wget -q http://apache.mirrors.spacedump.net/kafka/$KAFKA_VERSION/kafka_$SCALA_VERSION-$KAFKA_VERSION.tgz
  - tar xfz kafka_$SCALA_VERSION-$KAFKA_VERSION.tgz

script:
  - |
    ./kafka_$SCALA_VERSION-$KAFKA_VERSION/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test <<STDIN
    42
    STDIN
  - ./kafka_$SCALA_VERSION-$KAFKA_VERSION/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --max-messages 1 >> outfile
  - awk '$0 == "42"' outfile

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push d53dave/kafka;
    fi
