language: python
python:
    - "3.5"
    - "3.6"
    - "3.7dev"

dist: trusty
sudo: required

compiler:
  - gcc

before_script:
  - pip install pipenv
  - pipenv install --dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install libzmq3-dev libcapnp-dev capnproto g++-4.9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  - wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh --no-check-certificate -O cmake.sh
  - sudo sh cmake.sh --prefix=/usr/local --exclude-subdir
  - mkdir build
  - cd build
  - cmake ..

script: pipenv run py.test tests
