#!/usr/bin/env python

import sys
import click

from pyhocon import ConfigFactory


def check_python(major, minor):
    currentVersion = sys.version_info
    if currentVersion[0] == major and currentVersion[1] >= minor:
        pass
    else:
        sys.stderr.write("[%s] - Error: Your Python interpreter must be %d.%d or greater (within major version %d)\n" % (sys.argv[0], major, minor, major   ) )
        sys.exit(-1)
    return 0


@click.command()
@click.option('--config', '-c', default='conf/server.conf', type=click.Path(), help='Path to config file (default: conf/server.conf)')
@click.option('--port-data', '-d', default=-1, help='Port for data connections')
@click.option('--port-management', '-m', default=-1, help='Port for group management')
def csaopt_zmq(conf_path, port_data, port_management):
   conf = ConfigFactory.parse_file(conf_path)
   print('Got config file: ' +  conf.get_string(server.ports.data))


if __name__ == '__main__':
    check_python(3, 5)
    csaopt_zmq()